### ISSUE TITLE
//test:grakn-console-it should use real Grakn Core

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/console#1]
Right now, `//test:grakn-console-it` uses `@graknlabs_grakn_core//test-integration/rule:grakn-test-server`. This contributes to the cyclic dependency between grakn-core and console, and also does not demonstrate the "separation of concern" between the two code base. Console should test with a real and released version of Grakn Core.

**Comment by vmax** [comment]
This is addressed in #58 by using a real deployed artifact of Grakn Core for testing
