### ISSUE TITLE
Incorrect error message when the grakn server is not started

### ISSUE THREAD

**Issue by VladGan** [graknlabs/console#106]
## Description

When the Grakn server is not started and the user tries to run the command `databse list` in console, instead of showing a clear and understandable exception, the console prints an 
```io exception```
 message.

The same may be the case for the rest of the commands, but not tested.

## Expected Output

The message should indicate that the server is not started.

**Comment by lriuui0x0** [comment]
@VladGan Please can you work on this bug? It's likely that client-java is not throwing the right exception.

**Comment by vmax** [comment]
Duplicate of #108 which is already fixed
