### ISSUE TITLE
in grakn console, `transaction my_database schema rea` opens up a write transaction

### ISSUE THREAD

**Issue by JonThom** [graknlabs/console#127]
## Description

in grakn console, I accidentally hit enter after typing the incomplete command `transaction test schema rea` 
this then opened up a write transaction:
> test::schema::write> 

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): Grakn Core 2.0.0-alpha-6
3. Grakn client: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. `grakn server`
2. `grakn console`
3. `database create my_database`
3. `transaction my_database schema rea`

## Expected Output

> Unrecognised command, please check help menu

## Actual Output

> test::schema::write>

**Comment by haikalpribadi** [comment]
Thanks for raising this issue, @JonThom !! :) We've fixed this issue in commit https://github.com/graknlabs/console/commit/b96124d92bbe455a736620a971c876a794575b7c and it will come out in the next console release.
