### ISSUE TITLE
Console colours printed as special characters on Windows

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/console#134]
## Description

When receiving answers to a query the answers are returned with a jumble of special characters mixed in. I have observed this for Windows users only. The strong hypothesis is that desired text colours of the elements of the answer are printed incorrectly, which manifests as special characters. Smells strongly of a string format issue.

**Comment by lolski** [comment]
My suspicion is that Windows have their own colour code characters.

**Comment by haikalpribadi** [comment]
I think this is of higher priority, @jmsfltchr @lolski. This affects the user experience at the first point of entry. @vmax can you take this on?

**Comment by vmax** [comment]
@jmsfltchr @haikalpribadi @lolski I did a few tests on Windows and can confirm it's indeed an issue if you use CMD or PowerShell

![Cmd](https://user-images.githubusercontent.com/499267/111074189-edb5d180-84f2-11eb-9f1a-cc42eff0ce74.PNG)
![PowerShell](https://user-images.githubusercontent.com/499267/111074190-eee6fe80-84f2-11eb-9fa0-2ec32b6cc1f1.PNG)

However, there's a simple workaround that our users could do: use modern [Windows Terminal](https://github.com/microsoft/terminal)!

![WindowsTerminal](https://user-images.githubusercontent.com/499267/111074216-0c1bcd00-84f3-11eb-9ccc-d58937ab7ea7.PNG)

To ease the pain of those who *don't* use it, I suggest we add an argument to Console binary named `--nocolor` (or `--color=no`), which, as name suggests, would skip printing the escape codes.

**Comment by haikalpribadi** [comment]
can we detect the terminal at bootup of the console application and configure the colour options, @vmax ?

**Comment by vmax** [comment]
@haikalpribadi I verified it's possible to know if we're running under Windows Terminal by checking `WT_SESSION` presence of environment variable, [ref](https://stackoverflow.com/a/57362437). Therefore the heuristic for determining if we want to show colors would be:

```
if OS == Windows:
    if environment variable WT_SESSION is present:
        show colors
    else
        show colors
else:
    show colors
```

**Comment by haikalpribadi** [comment]
Where should you implement this heuristic, @vmax ? Do you know how to implement it?

**Comment by vmax** [comment]
@haikalpribadi os detection would probably go into `@graknlabs_common`; logic on enabling/disabling colors goes into Console. Yup, I'll implement this one.

**Comment by haikalpribadi** [comment]
I think it would be better if we can identify the OS in Java, and then configure the default colour setting also in Java, @vmax. I think that would be much cleaner. Is that possible?

**Comment by vmax** [comment]
@haikalpribadi all of the logic would be in Java, no doubt - it's just _which_ Java package to put it one. Sorry I wasn't clear on this one; when I said `@graknlabs_common` I in fact meant https://github.com/graknlabs/common/tree/master/util (**not** `grakn` or `grakn.bat` scripts)

**Comment by haikalpribadi** [comment]
Ah okay. Good. Let's do the logic in Java. Put the class in `grakn.common.util.`. Use the library in Console to determine if it should output colour.

**Comment by alexjpwalker** [comment]
Detecting if a user's terminal supports colours is actually pretty involved. Here's one (NodeJS based) tool designed to perform such detection: https://github.com/chalk/supports-color

**Comment by haikalpribadi** [comment]
well, I think we can just detect the OS like how max suggests above, right, @alexjpwalker ?

**Comment by alexjpwalker** [comment]
The thing is, it's not an OS-specific issue, but a terminal-specific one. The terminal I use most often when developing in Windows is the terminal built into Visual Studio Code, which does support colours - including on Windows.

So the most correct solution here is terminal detection, which - granted - is a little more involved than OS detection.

**Comment by vmax** [comment]
@haikalpribadi we went for a better and easier solution which just allows to print colors on Windows.
