### ISSUE TITLE
Automatically open and commit transactions

### ISSUE THREAD

**Issue by vmax** [graknlabs/console#19]
Currently, a transaction is opened after every `commit`/`rollback` statement and all statements entered are executed as part of one transaction. While the use case is legitimate (see ex.1), SQL shells generally execute every statement as its own transaction. Current behaviour can lead to users' confusion where they don't see changes committed from another session.

Ex.1:
>Say, you need to replace attribute marked as key and the only way to do that is to remove the existing attribute (1) and attach a new one (2). Committing automatically after (1) would throw an error

**Comment by lolski** [comment]
```
grakn> insert $p isa person;
$p committed
grakn> insert $p isa person;
$p committed
grakn> insert $p isa person;
$p committed
```

vs

```
grakn> :transaction
grakn> insert $p isa person;
grakn> insert $p isa person;
grakn> insert $p isa person;
grakn> :commit
Transaction committed
```

**Comment by lriuui0x0** [comment]
This is no longer what we wanted. We want explicit commit.
