### ISSUE TITLE
`keyspaces` is not recognised as an invalid command

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/console#34]
`keyspace` is now a valid console command. However, `keyspaces` also `startswith` `keyspace`, so we don't get an error in the console if the plural is used. We should resolve this to error out and print a help menu instead.

**Comment by vmax** [comment]
As of Console 2.0, this is no longer relevant given `keyspace` was renamed to `database` and it does exact matching (just "data") results in "Unrecognised command, please check help menu"
