### ISSUE TITLE
Console: automatically set query limit when not specified

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/console#56]
At the moment, it's possible for someone to write a query that produces a very long result, e.g. printing the database by doing `match $x isa thing; get;`. This may not be favourable in most cases, so let's automatically set the query limit (e.g. `limit 30;`) which the user can configure, and obviously also override.

**Comment by haikalpribadi** [comment]
The proposal was for Grakn Console (as opposed to the database server itself), but yes the output will print out the limit, which will also be included the query string printout as well, @JRWest2000.

I've also moved this issue to the Grakn Console repo.

**Comment by alexjpwalker** [comment]
Duplicate of #132 .
