### ISSUE TITLE
Console: keyspace management

### ISSUE THREAD

**Issue by grabl** [graknlabs/console#6]
_This issue was originally posted by @lolski  on 2017-09-26 18:05_.

We need a way of managing keyspaces in grakn, similar to `DROP DATABASE` or `CREATE DATABASE` in the SQL world.
My proposal is to do it through the graql console:

keyspace list
keyspace add <keyspace-name>
keyspace rename <from-name> <to-name>
keyspace delete <keyspace-name>

This issue needs graknlabs/grakn#3843, needs graknlabs/grakn#3862, needs graknlabs/grakn#4012

**Comment by lriuui0x0** [comment]
This is implemented.
