### ISSUE TITLE
"INTERNAL" appears at the start of the error message when Grakn throws an error

### ISSUE THREAD

**Issue by alexjpwalker** [graknlabs/console#72]
## Problem to Solve

"INTERNAL" appears at the start of the error message when Grakn throws an error

## Proposed Solution

INTERNAL is a gRPC status code.

We could hack it out by parsing the exception string, but the "right" solution here is most likely to extract the error message from the `StatusRuntimeException` and wrap that in a `GraknClientException`, without the status code.

All errors transmitted over gRPC are of type `StatusRuntimeException`.

This would be done in all Grakn clients - currently Java, Python and NodeJS.

**Comment by haikalpribadi** [comment]
What if we don't use GRPC's `StatusRuntimeException` at all from the backend, @alexjpwalker ? Would that be weird? 🤔 I'm thinking of this approach because it feels rather pointless if we wrap it in something (`StatusRuntimeException`) and then ask people to strip it out.

**Comment by alexjpwalker** [comment]
> What if we don't use GRPC's `StatusRuntimeException` at all from the backend, @alexjpwalker ? Would that be weird? 🤔 I'm thinking of this approach because it feels rather pointless if we wrap it in something (`StatusRuntimeException`) and then ask people to strip it out.

That would require us to implement our own Error message in protocol - a change that we do want to make eventually anyway; see https://github.com/graknlabs/client-java/issues/180 .

For sure, piggybacking on gRPC's `StatusRuntimeException` is basically a hack.

**Comment by haikalpribadi** [comment]
Okay let's discuss this tomorrow on what that exception would look like from the backend. It shouldn't take much effort to implement this once we know what it needs to look like.

**Comment by alexjpwalker** [comment]
Resolved in https://github.com/graknlabs/client-java/pull/178

**Comment by haikalpribadi** [comment]
Are you sure this issue is resolved in the Client Java PR you referred to, @alexjpwalker ? How so? I thought last time we discussed this issue, that PR was already merged?

**Comment by alexjpwalker** [comment]
It is definitely part of the PR, yes @haikalpribadi - see attached screenshot

![image](https://user-images.githubusercontent.com/14253102/99654831-cc683b80-2a52-11eb-9322-3fb7ea8cdfa4.png)

**Comment by haikalpribadi** [comment]
Right, I see that now! thanks @alexjpwalker
