### ISSUE TITLE
Console: Add `--force` flag to `grakn server clean` command

### ISSUE THREAD

**Issue by grabl** [graknlabs/console#9]
_This issue was originally posted by @haikalpribadi  on 2018-04-14 22:58_.

This is helpful when you want a script to clean a database without having to respond to an interactive "Yes/No" prompt

**Comment by vmax** [comment]
This is no longer relevant as of 2.0: cleaning the server data is as easy as just removing all folders inside of data directory; each database [keyspace] is self-contained now

**Comment by haikalpribadi** [comment]
> This is no longer relevant as of 2.0: cleaning the server data is as easy as just removing all folders inside of data directory; each database [keyspace] is self-contained now

Well, you shouldn't manually remove the folders. You should just `delete` the `database` using the `database delete` command, and that will wipe the data of that database, along with the `database` itself.
