### ISSUE TITLE
Cannot cancel process in console with ctrl-C

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/console#93]
After running a read query in the console, Grakn streams data back, but when I want to cancel that stream using "ctrl-c" nothing happens and the console seems to get stuck. 

1. Use this distro: https://www.dropbox.com/s/1y3ophwlv6xyg2z/grakn-2.0-alpha-tomas-20210109.zip?dl=0
2. Run match ($g, $p); ($p, $1);get $g;
3. Grakn starts to return data (while my CPU goes through the roof)
4. After a while it stops returning data (CPU still going through the roof)
5. At that point I can't use ctrl + c any more
6. I end up killing the GraknConsole process using kill -9, however, my CPU does not stop so I end up killing the Grakn process as well

![image](https://user-images.githubusercontent.com/20223184/104062800-00f6a900-51f3-11eb-8aa4-81da43cd1f11.png)

**Comment by haikalpribadi** [comment]
Does this only happen when the data is still currently being streamed, or also when the output stream has ended @tomassabat ?

**Comment by tomassabat** [comment]
> Does this only happen when the data is still currently being streamed, or also when the output stream has ended @tomassabat ?

So I've tested this a bit more. I report that most of the time ctrl + c works fine. 

But I did manage to reproduce the this bug by running a query that seems to hang. Please follow these steps: 
1. Use this distro: https://www.dropbox.com/s/1y3ophwlv6xyg2z/grakn-2.0-alpha-tomas-20210109.zip?dl=0
2. Run `match ($g, $p); ($p, $1);get $g;`
3. Grakn starts to return data (while my CPU goes through the roof)
4. After a while it stops returning data (CPU still going through the roof)
5. At that point I can't use ctrl + c any more 
6. I end up killing the GraknConsole process using `kill -9`, however, my CPU does not stop so I end up killing the Grakn process as well

**Comment by lriuui0x0** [comment]
It seems this issue should be fixed in grakn first

**Comment by VladGan** [comment]
@haikalpribadi @tomassabat the reason it hangs is that currently, you can cancel answers stream only in between answers. So if you pressed `ctrl+c` in the middle of the answer calculation, the server will only stop once it is finished with the current answer, and it may take some time. 

There are 2 possible solutions I see for this particular case: Ctrl+C will cancel only the console side and will allow the user to run a new query, although old one will be still running on server. Or, change the server to handle terminate requests on a more granular level than between answers
